yaml
name: AutoLLM Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.requirements_file }}
      - name: Run automated pipeline
        run: |
          ${{ env.test_command }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: auto-llm-artifacts
          path: ${{ env.artifacts_path }}