yaml
name: AutoLLM Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auto_llm/requirements.txt
      - name: Run automated pipeline
        run: |
          python -m pytest auto_llm/auto_exec/tests/test_calculation.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: auto-llm-artifacts
          path: /home/Newdisk2/aofanyu/project/autotask/auto_llm/artifacts