yaml
name: AutoLLM Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_FILE }}
        env:
          REQUIREMENTS_FILE: ${{ env.REQUIREMENTS_FILE }}
      - name: Run automated pipeline
        run: |
          ${{ env.TEST_COMMAND }}
        env:
          TEST_COMMAND: ${{ env.TEST_COMMAND }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auto-llm-artifacts
          path: ${{ env.ARTIFACTS_PATH }}
        env:
          ARTIFACTS_PATH: ${{ env.ARTIFACTS_PATH }}