yaml
name: AutoLLM Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_FILE }}
        env:
          REQUIREMENTS_FILE: ${{ env.requirements_file }}
      - name: Run automated pipeline
        run: |
          python ${{ env.TEST_COMMAND }}
        env:
          TEST_COMMAND: ${{ env.test_command }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: auto-llm-artifacts
          path: ${{ env.ARTIFACTS_PATH }}
        env:
          ARTIFACTS_PATH: ${{ env.artifacts_path }}