yaml
name: Element Detection Suite

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.requirements_file }}
        env:
          requirements_file: ${{ env.entry_point }}/../../../auto_llm/requirements.txt
      - name: Run automated pipeline
        run: |
          ${{ env.test_command }}
        env:
          test_command: python -m pytest ${{ env.entry_point }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auto-llm-artifacts
          path: ${{ env.artifacts_path }}
        env:
          artifacts_path: /home/Newdisk2/aofanyu/project/autotask/auto_llm/artifacts