yaml
name: AutoLLM Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements_file }}
        with:
          requirements_file: auto_llm/requirements.txt
      - name: Run automated pipeline
        run: |
          python ${{ inputs.test_command }}
        with:
          test_command: python -m pytest auto_llm/auto_exec/tests/test_generated.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: auto-llm-artifacts
          path: ${{ inputs.artifacts_path }}
        with:
          artifacts_path: /home/Newdisk2/aofanyu/project/autotask/auto_llm/artifacts